# Generated by Django 4.0.3 on 2024-06-10 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendacion', '0005_remove_ejercicio_nivel_asignatura_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='nivel',
            name='nombre',
            field=models.CharField(default=None, max_length=100, verbose_name='Nombre'),
            preserve_default=False,
        ),
    ]
