# Generated by Django 4.0.3 on 2024-06-10 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recomendacion', '0006_nivel_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asignatura',
            old_name='foto',
            new_name='imagen',
        ),
    ]
