# Generated by Django 4.0.3 on 2024-06-14 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recomendacion', '0007_rename_foto_asignatura_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='asignatura',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='recomendacion.asignatura', verbose_name='Asignatura'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
                ('fechaInscripcion', models.DateTimeField(auto_now_add=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recomendacion.asignatura', verbose_name='Asignatura')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recomendacion.persona', verbose_name='Persona')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
                'permissions': (('exportar_inscripcion', 'puede exportar inscripcion'),),
            },
        ),
    ]
