# Generated by Django 4.0.3 on 2024-03-06 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
                ('nombre', models.CharField(default='', max_length=140, verbose_name='Titulo')),
                ('descripcion', models.CharField(blank=True, default='', max_length=140, null=True, verbose_name='Descripcion')),
                ('icono', models.ImageField(blank=True, null=True, upload_to='icono/', verbose_name='icono')),
                ('ruta', models.CharField(default='', max_length=140, verbose_name='Ruta')),
                ('es_principal', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('acceso', models.ManyToManyField(to='auth.group', verbose_name='acceso')),
                ('principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recomendacion.menu')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menus',
                'permissions': (('exportar_menu', 'puede exportar menu'),),
            },
        ),
        migrations.CreateModel(
            name='Sitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
                ('nombresitio', models.CharField(default='', max_length=140, verbose_name='NombreSitio')),
                ('icono', models.ImageField(blank=True, null=True, upload_to='icono/', verbose_name='icono')),
                ('favicono', models.ImageField(blank=True, null=True, upload_to='favicono/', verbose_name='favicono')),
                ('correo', models.EmailField(default='', max_length=140, verbose_name='correo')),
                ('clave', models.CharField(default='', max_length=140, verbose_name='clave')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sitio',
                'verbose_name_plural': 'Sitios',
                'permissions': (('exportar_sitio', 'puede exportar sitio'),),
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
                ('cedula', models.CharField(default='', max_length=10, verbose_name='Cedula')),
                ('nombres', models.CharField(default='', max_length=140, verbose_name='Nombre')),
                ('apellidos', models.CharField(default='', max_length=60, verbose_name='Apellido')),
                ('correo', models.EmailField(default='', max_length=140, verbose_name='Correo')),
                ('sexo', models.IntegerField(blank=True, choices=[(1, 'MASCULINO'), (2, 'FEMENINO')], default=1, null=True, verbose_name='Sexo')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('foto', models.FileField(blank=True, null=True, upload_to='foto/%Y/%m/%d')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['apellidos'],
                'permissions': (('exportar_persona', 'puede exportar persona'),),
            },
        ),
        migrations.CreateModel(
            name='MenuPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recomendacion.menu', verbose_name='Menu')),
                ('perfil', models.ManyToManyField(to='auth.group', verbose_name='Perfil')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Menu Perfil',
                'verbose_name_plural': 'Menu Perfiles',
                'permissions': (('exportar_menuperfil', 'puede exportar menu perfil'),),
            },
        ),
    ]
