# Generated by Django 4.0.3 on 2024-06-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendacion', '0008_ejercicio_asignatura_inscripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejercicio',
            name='contenido',
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='contenido',
            field=models.ManyToManyField(to='recomendacion.contenido', verbose_name='Contenido'),
        ),
    ]
